// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: people.proto

package is1.protomodel;

public final class PeopleProto {
  private PeopleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_is1_People_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_is1_People_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_is1_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_is1_Person_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014people.proto\022\003is1\"F\n\006People\022\n\n\002id\030\001 \002(" +
      "\005\022\017\n\007orgName\030\002 \002(\t\022\037\n\npeopleList\030\003 \003(\0132\013" +
      ".is1.Person\"1\n\006Person\022\n\n\002id\030\001 \002(\005\022\014\n\004nam" +
      "e\030\002 \002(\t\022\r\n\005email\030\003 \002(\tB\037\n\016is1.protomodel" +
      "B\013PeopleProtoP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_is1_People_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_is1_People_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_is1_People_descriptor,
        new java.lang.String[] { "Id", "OrgName", "PeopleList", });
    internal_static_is1_Person_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_is1_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_is1_Person_descriptor,
        new java.lang.String[] { "Id", "Name", "Email", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
