// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: people.proto

package is1.protomodel;

/**
 * Protobuf type {@code is1.People}
 */
public final class People extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:is1.People)
    PeopleOrBuilder {
private static final long serialVersionUID = 0L;
  // Use People.newBuilder() to construct.
  private People(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private People() {
    orgName_ = "";
    peopleList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new People();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return is1.protomodel.PeopleProto.internal_static_is1_People_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return is1.protomodel.PeopleProto.internal_static_is1_People_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            is1.protomodel.People.class, is1.protomodel.People.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_ = 0;
  /**
   * <code>required int32 id = 1;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required int32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int ORGNAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object orgName_ = "";
  /**
   * <code>required string orgName = 2;</code>
   * @return Whether the orgName field is set.
   */
  @java.lang.Override
  public boolean hasOrgName() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required string orgName = 2;</code>
   * @return The orgName.
   */
  @java.lang.Override
  public java.lang.String getOrgName() {
    java.lang.Object ref = orgName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        orgName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string orgName = 2;</code>
   * @return The bytes for orgName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOrgNameBytes() {
    java.lang.Object ref = orgName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      orgName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PEOPLELIST_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<is1.protomodel.Person> peopleList_;
  /**
   * <code>repeated .is1.Person peopleList = 3;</code>
   */
  @java.lang.Override
  public java.util.List<is1.protomodel.Person> getPeopleListList() {
    return peopleList_;
  }
  /**
   * <code>repeated .is1.Person peopleList = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends is1.protomodel.PersonOrBuilder> 
      getPeopleListOrBuilderList() {
    return peopleList_;
  }
  /**
   * <code>repeated .is1.Person peopleList = 3;</code>
   */
  @java.lang.Override
  public int getPeopleListCount() {
    return peopleList_.size();
  }
  /**
   * <code>repeated .is1.Person peopleList = 3;</code>
   */
  @java.lang.Override
  public is1.protomodel.Person getPeopleList(int index) {
    return peopleList_.get(index);
  }
  /**
   * <code>repeated .is1.Person peopleList = 3;</code>
   */
  @java.lang.Override
  public is1.protomodel.PersonOrBuilder getPeopleListOrBuilder(
      int index) {
    return peopleList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasOrgName()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getPeopleListCount(); i++) {
      if (!getPeopleList(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, orgName_);
    }
    for (int i = 0; i < peopleList_.size(); i++) {
      output.writeMessage(3, peopleList_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, orgName_);
    }
    for (int i = 0; i < peopleList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, peopleList_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof is1.protomodel.People)) {
      return super.equals(obj);
    }
    is1.protomodel.People other = (is1.protomodel.People) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (getId()
          != other.getId()) return false;
    }
    if (hasOrgName() != other.hasOrgName()) return false;
    if (hasOrgName()) {
      if (!getOrgName()
          .equals(other.getOrgName())) return false;
    }
    if (!getPeopleListList()
        .equals(other.getPeopleListList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
    }
    if (hasOrgName()) {
      hash = (37 * hash) + ORGNAME_FIELD_NUMBER;
      hash = (53 * hash) + getOrgName().hashCode();
    }
    if (getPeopleListCount() > 0) {
      hash = (37 * hash) + PEOPLELIST_FIELD_NUMBER;
      hash = (53 * hash) + getPeopleListList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static is1.protomodel.People parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static is1.protomodel.People parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static is1.protomodel.People parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static is1.protomodel.People parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static is1.protomodel.People parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static is1.protomodel.People parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static is1.protomodel.People parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static is1.protomodel.People parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static is1.protomodel.People parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static is1.protomodel.People parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static is1.protomodel.People parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static is1.protomodel.People parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(is1.protomodel.People prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code is1.People}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:is1.People)
      is1.protomodel.PeopleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return is1.protomodel.PeopleProto.internal_static_is1_People_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return is1.protomodel.PeopleProto.internal_static_is1_People_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              is1.protomodel.People.class, is1.protomodel.People.Builder.class);
    }

    // Construct using is1.protomodel.People.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0;
      orgName_ = "";
      if (peopleListBuilder_ == null) {
        peopleList_ = java.util.Collections.emptyList();
      } else {
        peopleList_ = null;
        peopleListBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return is1.protomodel.PeopleProto.internal_static_is1_People_descriptor;
    }

    @java.lang.Override
    public is1.protomodel.People getDefaultInstanceForType() {
      return is1.protomodel.People.getDefaultInstance();
    }

    @java.lang.Override
    public is1.protomodel.People build() {
      is1.protomodel.People result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public is1.protomodel.People buildPartial() {
      is1.protomodel.People result = new is1.protomodel.People(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(is1.protomodel.People result) {
      if (peopleListBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          peopleList_ = java.util.Collections.unmodifiableList(peopleList_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.peopleList_ = peopleList_;
      } else {
        result.peopleList_ = peopleListBuilder_.build();
      }
    }

    private void buildPartial0(is1.protomodel.People result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.orgName_ = orgName_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof is1.protomodel.People) {
        return mergeFrom((is1.protomodel.People)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(is1.protomodel.People other) {
      if (other == is1.protomodel.People.getDefaultInstance()) return this;
      if (other.hasId()) {
        setId(other.getId());
      }
      if (other.hasOrgName()) {
        orgName_ = other.orgName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (peopleListBuilder_ == null) {
        if (!other.peopleList_.isEmpty()) {
          if (peopleList_.isEmpty()) {
            peopleList_ = other.peopleList_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensurePeopleListIsMutable();
            peopleList_.addAll(other.peopleList_);
          }
          onChanged();
        }
      } else {
        if (!other.peopleList_.isEmpty()) {
          if (peopleListBuilder_.isEmpty()) {
            peopleListBuilder_.dispose();
            peopleListBuilder_ = null;
            peopleList_ = other.peopleList_;
            bitField0_ = (bitField0_ & ~0x00000004);
            peopleListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPeopleListFieldBuilder() : null;
          } else {
            peopleListBuilder_.addAllMessages(other.peopleList_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasId()) {
        return false;
      }
      if (!hasOrgName()) {
        return false;
      }
      for (int i = 0; i < getPeopleListCount(); i++) {
        if (!getPeopleList(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              orgName_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              is1.protomodel.Person m =
                  input.readMessage(
                      is1.protomodel.Person.PARSER,
                      extensionRegistry);
              if (peopleListBuilder_ == null) {
                ensurePeopleListIsMutable();
                peopleList_.add(m);
              } else {
                peopleListBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>required int32 id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>required int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object orgName_ = "";
    /**
     * <code>required string orgName = 2;</code>
     * @return Whether the orgName field is set.
     */
    public boolean hasOrgName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string orgName = 2;</code>
     * @return The orgName.
     */
    public java.lang.String getOrgName() {
      java.lang.Object ref = orgName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          orgName_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string orgName = 2;</code>
     * @return The bytes for orgName.
     */
    public com.google.protobuf.ByteString
        getOrgNameBytes() {
      java.lang.Object ref = orgName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orgName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string orgName = 2;</code>
     * @param value The orgName to set.
     * @return This builder for chaining.
     */
    public Builder setOrgName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      orgName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>required string orgName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrgName() {
      orgName_ = getDefaultInstance().getOrgName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>required string orgName = 2;</code>
     * @param value The bytes for orgName to set.
     * @return This builder for chaining.
     */
    public Builder setOrgNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      orgName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.util.List<is1.protomodel.Person> peopleList_ =
      java.util.Collections.emptyList();
    private void ensurePeopleListIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        peopleList_ = new java.util.ArrayList<is1.protomodel.Person>(peopleList_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        is1.protomodel.Person, is1.protomodel.Person.Builder, is1.protomodel.PersonOrBuilder> peopleListBuilder_;

    /**
     * <code>repeated .is1.Person peopleList = 3;</code>
     */
    public java.util.List<is1.protomodel.Person> getPeopleListList() {
      if (peopleListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(peopleList_);
      } else {
        return peopleListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .is1.Person peopleList = 3;</code>
     */
    public int getPeopleListCount() {
      if (peopleListBuilder_ == null) {
        return peopleList_.size();
      } else {
        return peopleListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .is1.Person peopleList = 3;</code>
     */
    public is1.protomodel.Person getPeopleList(int index) {
      if (peopleListBuilder_ == null) {
        return peopleList_.get(index);
      } else {
        return peopleListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .is1.Person peopleList = 3;</code>
     */
    public Builder setPeopleList(
        int index, is1.protomodel.Person value) {
      if (peopleListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePeopleListIsMutable();
        peopleList_.set(index, value);
        onChanged();
      } else {
        peopleListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .is1.Person peopleList = 3;</code>
     */
    public Builder setPeopleList(
        int index, is1.protomodel.Person.Builder builderForValue) {
      if (peopleListBuilder_ == null) {
        ensurePeopleListIsMutable();
        peopleList_.set(index, builderForValue.build());
        onChanged();
      } else {
        peopleListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .is1.Person peopleList = 3;</code>
     */
    public Builder addPeopleList(is1.protomodel.Person value) {
      if (peopleListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePeopleListIsMutable();
        peopleList_.add(value);
        onChanged();
      } else {
        peopleListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .is1.Person peopleList = 3;</code>
     */
    public Builder addPeopleList(
        int index, is1.protomodel.Person value) {
      if (peopleListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePeopleListIsMutable();
        peopleList_.add(index, value);
        onChanged();
      } else {
        peopleListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .is1.Person peopleList = 3;</code>
     */
    public Builder addPeopleList(
        is1.protomodel.Person.Builder builderForValue) {
      if (peopleListBuilder_ == null) {
        ensurePeopleListIsMutable();
        peopleList_.add(builderForValue.build());
        onChanged();
      } else {
        peopleListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .is1.Person peopleList = 3;</code>
     */
    public Builder addPeopleList(
        int index, is1.protomodel.Person.Builder builderForValue) {
      if (peopleListBuilder_ == null) {
        ensurePeopleListIsMutable();
        peopleList_.add(index, builderForValue.build());
        onChanged();
      } else {
        peopleListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .is1.Person peopleList = 3;</code>
     */
    public Builder addAllPeopleList(
        java.lang.Iterable<? extends is1.protomodel.Person> values) {
      if (peopleListBuilder_ == null) {
        ensurePeopleListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, peopleList_);
        onChanged();
      } else {
        peopleListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .is1.Person peopleList = 3;</code>
     */
    public Builder clearPeopleList() {
      if (peopleListBuilder_ == null) {
        peopleList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        peopleListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .is1.Person peopleList = 3;</code>
     */
    public Builder removePeopleList(int index) {
      if (peopleListBuilder_ == null) {
        ensurePeopleListIsMutable();
        peopleList_.remove(index);
        onChanged();
      } else {
        peopleListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .is1.Person peopleList = 3;</code>
     */
    public is1.protomodel.Person.Builder getPeopleListBuilder(
        int index) {
      return getPeopleListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .is1.Person peopleList = 3;</code>
     */
    public is1.protomodel.PersonOrBuilder getPeopleListOrBuilder(
        int index) {
      if (peopleListBuilder_ == null) {
        return peopleList_.get(index);  } else {
        return peopleListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .is1.Person peopleList = 3;</code>
     */
    public java.util.List<? extends is1.protomodel.PersonOrBuilder> 
         getPeopleListOrBuilderList() {
      if (peopleListBuilder_ != null) {
        return peopleListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(peopleList_);
      }
    }
    /**
     * <code>repeated .is1.Person peopleList = 3;</code>
     */
    public is1.protomodel.Person.Builder addPeopleListBuilder() {
      return getPeopleListFieldBuilder().addBuilder(
          is1.protomodel.Person.getDefaultInstance());
    }
    /**
     * <code>repeated .is1.Person peopleList = 3;</code>
     */
    public is1.protomodel.Person.Builder addPeopleListBuilder(
        int index) {
      return getPeopleListFieldBuilder().addBuilder(
          index, is1.protomodel.Person.getDefaultInstance());
    }
    /**
     * <code>repeated .is1.Person peopleList = 3;</code>
     */
    public java.util.List<is1.protomodel.Person.Builder> 
         getPeopleListBuilderList() {
      return getPeopleListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        is1.protomodel.Person, is1.protomodel.Person.Builder, is1.protomodel.PersonOrBuilder> 
        getPeopleListFieldBuilder() {
      if (peopleListBuilder_ == null) {
        peopleListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            is1.protomodel.Person, is1.protomodel.Person.Builder, is1.protomodel.PersonOrBuilder>(
                peopleList_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        peopleList_ = null;
      }
      return peopleListBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:is1.People)
  }

  // @@protoc_insertion_point(class_scope:is1.People)
  private static final is1.protomodel.People DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new is1.protomodel.People();
  }

  public static is1.protomodel.People getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<People>
      PARSER = new com.google.protobuf.AbstractParser<People>() {
    @java.lang.Override
    public People parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<People> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<People> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public is1.protomodel.People getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

