// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: people.proto

package is1.protomodel;

public interface PeopleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:is1.People)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>required int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>required string orgName = 2;</code>
   * @return Whether the orgName field is set.
   */
  boolean hasOrgName();
  /**
   * <code>required string orgName = 2;</code>
   * @return The orgName.
   */
  java.lang.String getOrgName();
  /**
   * <code>required string orgName = 2;</code>
   * @return The bytes for orgName.
   */
  com.google.protobuf.ByteString
      getOrgNameBytes();

  /**
   * <code>repeated .is1.Person peopleList = 3;</code>
   */
  java.util.List<is1.protomodel.Person> 
      getPeopleListList();
  /**
   * <code>repeated .is1.Person peopleList = 3;</code>
   */
  is1.protomodel.Person getPeopleList(int index);
  /**
   * <code>repeated .is1.Person peopleList = 3;</code>
   */
  int getPeopleListCount();
  /**
   * <code>repeated .is1.Person peopleList = 3;</code>
   */
  java.util.List<? extends is1.protomodel.PersonOrBuilder> 
      getPeopleListOrBuilderList();
  /**
   * <code>repeated .is1.Person peopleList = 3;</code>
   */
  is1.protomodel.PersonOrBuilder getPeopleListOrBuilder(
      int index);
}
